# แผนการสอนประจำหน่วย {.unnumbered}

### **ชุดวิชา**

หลักวิทยาการข้อมูลและการแสดงผลด้วยแผนภาพ

### **หน่วยที่ 4**

การเตรียมข้อมูล

### **ตอนที่**

4.1 การนำเข้าและเขียนชุดข้อมูล

4.2 การจัดระเบียบข้อมูล

4.2 การจัดกระทำข้อมูล

4.3 การวิเคราะห์เพื่อสำรวจข้อมูลและการแก้ปัญหา

### **แนวคิด**

ขั้นตอนการดำเนินงานทางด้านวิทยาการข้อมูลอาจจำแนกออกเป็น 5 ขั้นตอนใหญ่ได้แก่ การระบุปัญหา/วัตถุประสงค์ของงาน การเก็บรวบรวมข้อมูล การเตรียมข้อมูล การวิเคราะห์ข้อมูล/การพัฒนาโมเดล และการนำผลการวิเคราะห์/โมเดลไปใช้งาน

ส่วนประกอบสำคัญที่สุดในการดำเนินงานทางด้านสถิติและวิทยาการข้อมูลคือข้อมูล ถึงแม้ว่าปัจจุบันข้อมูลจะเป็นทรัพยากรที่มีอยู่จำนวนมาก และสามารถเข้าถึงได้โดยง่าย แต่ในสถานการณ์ของการทำงานจริง ข้อมูลส่วนใหญ่มักยังไม่อยู่ในสภาพที่พร้อมสำหรับการนำไปดำเนินการวิเคราะห์ตามวัตถุประสงค์ต่าง ๆ การเตรียมข้อมูลจึงเป็นขั้นตอนสำคัญที่นักสถิติและนักวิทยาการข้อมูลต้องดำเนินการ เพื่อจัดระเบียบหรือจัดกระทำข้อมูล ในเชิงปฏิบัติการเตรียมข้อมูลเป็นขั้นตอนที่ใช้ทรัพยากรและเวลาค่อนข้างมาก กล่าวกันว่าขั้นตอนนี้ใช้เวลาในการดำเนินงานคิดเป็นกว่าร้อยละ 80 ของการดำเนินงานทั้งหมดของโครงการวิทยาการข้อมูล (Dasu, & Johnson, 2003) นอกจากนี้การเตรียมข้อมูลนี้ยังมีลักษณะการดำเนินงานเป็นแบบทวนซ้ำไปมาหลายครั้ง และไม่ได้มีรูปแบบการดำเนินงานที่ตายตัวเหมือนกันในแต่ละโครงการ ความรู้และทักษะนี้จึงมีความจำเป็นอย่างยิ่งสำหรับนักสถิติและนักวิทยาการข้อมูล

เพื่อให้ผู้อ่านมีความรู้และทักษะที่เพียงพอสำหรับการเตรียมข้อมูล เนื้อหาภายในหน่วยการเรียนนี้จึงประกอบด้วย มโนทัศน์และวิธีการที่จำเป็นสำหรับการเตรียมข้อมูลดังกล่าว ประกอบด้วย การจัดระเบียบชุดข้อมูล การจัดกระทำข้อมูล การวิเคราะห์เพื่อสำรวจข้อมูล และการแก้ปัญหาที่เกิดขึ้นในข้อมูลได้แก่ ปัญหาค่าสูญหาย และปัญหาค่าผิดปกติ โดยผู้เขียนได้แทรกตัวอย่างและชุดคำสั่งของภาษา R และภาษา Python สำหรับใช้การดำเนินการต่าง ๆ ในข้างต้น ซึ่งผู้อ่านสามารถนำชุดคำสั่งที่ให้ในบทเรียนไปประยุกต์ใช้ได้ในการทำงาน

### **วัตถุประสงค์**

เมื่อศึกษาหน่วยที่ 4 จบแล้วผู้อ่านสามารถ

1.  นำเข้าและเขียนชุดข้อมูลได้
2.  อธิบายมโนทัศน์ของชุดข้อมูลจัดระเบียบ
3.  สำรวจสภาพและระบุปัญหาที่เกิดขึ้นในชุดข้อมูล โดยใช้สถิติพื้นฐานและทัศนภาพข้อมูล
4.  จัดระเบียบชุดข้อมูลให้อยู่ในรูปแบบตารางข้อมูลที่เหมาะสมสำหรับการวิเคราะห์ข้อมูล
5.  จัดกระทำข้อมูลเพื่อให้ได้ชุดข้อมูลที่เหมาะสมและตรงกับความต้องการในการวิเคราะห์ข้อมูล
6.  อธิบายมโนทัศน์ของค่าสูญหายได้ สามารถวิเคราะห์และทดแทนค่าสูญหายได้อย่างเหมาะสม
7.  อธิบายมโนทัศน์ของค่าผิดปกติได้ สามารถวิเคราะห์และแก้ปัญหาค่าผิดปกติได้อย่างเหมาะสม
